[bugzilla]
products = ["SUSE Manager 4.0", "SUSE Manager 4.1", "SUSE Manager 4.2", "SUSE Manager 4.3"]
url = "bugzilla.suse.com"
username = "<user>"
password = "<password>"
apikey = "<api_key_from_bugzilla>"
use_legacy_credentials = false
sslverify = false

[questdb]
user = "admin"
password = "quest"
host = "127.0.0.1"
port = "8812"
database = "qdb"
